/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.milton.gomez.sistema.universitario.View.Panels.Alumno;

import com.milton.gomez.sistema.universitario.Controller.ControllerAlumno;
import com.milton.gomez.sistema.universitario.Transferible.TransferibleAlumno;
import com.milton.gomez.sistema.universitario.View.ViewMain;
import javax.swing.DefaultListModel;

/**
 *
 * @author milton
 */
public class DetallesAlumno extends javax.swing.JPanel {

    private Integer alumnoID;
    /**
     * Creates new form DetallesAlumno
     * @param alumnoID
     */
    public DetallesAlumno(Integer alumnoID) {
        initComponents();
        initDetalles(alumnoID);
    }
    
    private void initDetalles(Integer alumnoID){
        this.alumnoID = alumnoID;
        TransferibleAlumno alumno = ControllerAlumno.obtenerDatosDeAlumno(alumnoID);
        Title_Label.setText(alumno.getNombre() + " " + alumno.getApellido());
        ID_Label.setText(alumno.getId().toString());
        Legajo_Label.setText(alumno.getLegajo().toString());
        DNI_Label.setText(alumno.getDni().toString());
        Carrera_Label.setText(alumno.getCarrera().toString());
        MateriasQuePuedeCursar_List.setModel(ControllerAlumno.obtenerMateriasQuePuedeCursar(alumnoID, MateriasQuePuedeCursar_List));
        Cursadas_List.setModel(ControllerAlumno.obtenerMateriasCursando(alumnoID, Cursadas_List));
        Aprobadas_List.setModel(ControllerAlumno.obtenerMateriasAprobadas(alumnoID, Aprobadas_List));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_Panel = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Body_Panel = new javax.swing.JPanel();
        Datos_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID_Label = new javax.swing.JLabel();
        Legajo_Label = new javax.swing.JLabel();
        DNI_Label = new javax.swing.JLabel();
        Carrera_Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cursadas_List = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Aprobadas_List = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MateriasQuePuedeCursar_List = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        Inscribirse_Button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(780, 580));

        Title_Label.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Title_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person_icon.png"))); // NOI18N

        javax.swing.GroupLayout Title_PanelLayout = new javax.swing.GroupLayout(Title_Panel);
        Title_Panel.setLayout(Title_PanelLayout);
        Title_PanelLayout.setHorizontalGroup(
            Title_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_PanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(Title_Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Title_PanelLayout.setVerticalGroup(
            Title_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title_PanelLayout.createSequentialGroup()
                .addComponent(Title_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel2.setText("Legajo:");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel4.setText("Carrera:");

        ID_Label.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N

        Legajo_Label.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N

        DNI_Label.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N

        Carrera_Label.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N

        javax.swing.GroupLayout Datos_PanelLayout = new javax.swing.GroupLayout(Datos_Panel);
        Datos_Panel.setLayout(Datos_PanelLayout);
        Datos_PanelLayout.setHorizontalGroup(
            Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Datos_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ID_Label))
                    .addGroup(Datos_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Legajo_Label))
                    .addGroup(Datos_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(DNI_Label))
                    .addGroup(Datos_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Carrera_Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Datos_PanelLayout.setVerticalGroup(
            Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ID_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Legajo_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(DNI_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Datos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Carrera_Label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel5.setText("Materias que Cursa");

        Cursadas_List.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Cursadas_List.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(Cursadas_List);

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel6.setText("Materias Aprobadas");

        Aprobadas_List.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Aprobadas_List.setModel(new DefaultListModel<>());
        jScrollPane2.setViewportView(Aprobadas_List);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel7.setText("Datos del Alumno");

        jScrollPane3.setMaximumSize(new java.awt.Dimension(277, 133));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(277, 133));

        MateriasQuePuedeCursar_List.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        MateriasQuePuedeCursar_List.setModel(new DefaultListModel<>());
        MateriasQuePuedeCursar_List.setToolTipText("");
        MateriasQuePuedeCursar_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane3.setViewportView(MateriasQuePuedeCursar_List);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel8.setText("Materias que puede cursar");

        Inscribirse_Button.setBackground(new java.awt.Color(204, 0, 0));
        Inscribirse_Button.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        Inscribirse_Button.setForeground(new java.awt.Color(255, 255, 255));
        Inscribirse_Button.setText("Inscribirse");
        Inscribirse_Button.setBorderPainted(false);
        Inscribirse_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inscribirse_ButtonActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout Body_PanelLayout = new javax.swing.GroupLayout(Body_Panel);
        Body_Panel.setLayout(Body_PanelLayout);
        Body_PanelLayout.setHorizontalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Body_PanelLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Inscribirse_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Body_PanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8))
                            .addComponent(Datos_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7)))
                .addGap(67, 67, 67)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(64, 64, 64))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(114, 114, 114))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)))))
        );
        Body_PanelLayout.setVerticalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Body_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Datos_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Body_PanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Body_PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Inscribirse_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Inscribirse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inscribirse_ButtonActionPerformed
        if(MateriasQuePuedeCursar_List.getSelectedIndices().length != 0){
            ControllerAlumno.inscribirAlumno(alumnoID, MateriasQuePuedeCursar_List.getSelectedValuesList());
            javax.swing.JOptionPane.showMessageDialog(this, "El alumno se inscribió exitosamente a la/las materias. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            ViewMain.ShowJPanel(new DetallesAlumno(alumnoID));
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar minimamente una materia. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Inscribirse_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<com.milton.gomez.sistema.universitario.Model.Materia> Aprobadas_List;
    private javax.swing.JPanel Body_Panel;
    private javax.swing.JLabel Carrera_Label;
    private javax.swing.JList<com.milton.gomez.sistema.universitario.Model.Materia> Cursadas_List;
    private javax.swing.JLabel DNI_Label;
    private javax.swing.JPanel Datos_Panel;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JButton Inscribirse_Button;
    private javax.swing.JLabel Legajo_Label;
    private javax.swing.JList<com.milton.gomez.sistema.universitario.Model.Materia> MateriasQuePuedeCursar_List;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JPanel Title_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
