/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.milton.gomez.sistema.universitario.View.Panels.Materias;

import com.milton.gomez.sistema.universitario.Controller.ControllerCarrera;
import com.milton.gomez.sistema.universitario.Controller.ControllerMateria;
import com.milton.gomez.sistema.universitario.Model.Materia;
import com.milton.gomez.sistema.universitario.Transferible.TransferibleMateria;
import com.milton.gomez.sistema.universitario.View.ViewMain;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class SubirMateriaPanel extends javax.swing.JPanel {

    
    private Integer materiaId;
    private Boolean isEdicion = false;
    
    
    public SubirMateriaPanel() {
        initComponents();
        listarMaterias();
    }
    
    public SubirMateriaPanel(Integer id) {
        initComponents();
        listarMaterias();
        this.materiaId = id;
        this.isEdicion = true;
        editableView();
    }

    private void editableView(){
        Materia materia = ControllerMateria.obtenerMateria(materiaId);
        
        
        
        tituloLabel.setText("Editar Materia");
        nombreTextField.setText(materia.getNombre());
        codigoTextField.setText(materia.getCodigoDeMateria());
        promocionableCheckBox.setSelected(materia.isPromocionable());
        
        //Seleccionar elementos de la lista de materias
        DefaultListModel<Materia> listModel = (DefaultListModel<Materia>) materiasList.getModel();
        
        List<Integer> indicesSeleccionados = new ArrayList<>();
        for (int i = 0; i < listModel.size(); i++) {
            if (materia.getCorrelativas().contains(listModel.get(i))) {
                indicesSeleccionados.add(i);
            }
        }
        
        // conversion
        int[] indices = indicesSeleccionados.stream().mapToInt(Integer::intValue).toArray();

        materiasList.setSelectedIndices(indices);
        
    }
    
    private void listarMaterias(){
        DefaultListModel<Materia> listModel = (DefaultListModel<Materia>) materiasList.getModel();
        listModel.clear();
        ControllerMateria.listarTodasLasMaterias().forEach(m -> listModel.addElement(m));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        Separador_Separator = new javax.swing.JSeparator();
        tituloLabel = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materiasList = new javax.swing.JList<>();
        nombreTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        promocionableCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Subir_Button = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(782, 580));

        tituloLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materia_icon.png"))); // NOI18N
        tituloLabel.setText("Crear nueva Materia");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(tituloLabel))
                    .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Nombre *");

        materiasList.setModel(new DefaultListModel<>());
        jScrollPane1.setViewportView(materiasList);

        nombreTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Codigo *");

        codigoTextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        codigoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextFieldActionPerformed(evt);
            }
        });

        promocionableCheckBox.setText("Promocionable");
        promocionableCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionableCheckBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Seleccione las correlativas");

        Subir_Button.setBackground(new java.awt.Color(204, 0, 0));
        Subir_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Subir_Button.setForeground(new java.awt.Color(255, 255, 255));
        Subir_Button.setText("Subir");
        Subir_Button.setBorderPainted(false);
        Subir_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subir_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(nombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(codigoTextField))
                    .addComponent(promocionableCheckBox))
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Subir_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))))
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyPanelLayout.createSequentialGroup()
                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(promocionableCheckBox))
                    .addComponent(jScrollPane1))
                .addGap(157, 157, 157)
                .addComponent(Subir_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void codigoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextFieldActionPerformed

    private void promocionableCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocionableCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promocionableCheckBoxActionPerformed

    private void Subir_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subir_ButtonActionPerformed
        try{
            if(!nombreTextField.getText().isBlank() && !codigoTextField.getText().isBlank()){
                TransferibleMateria transferible = new TransferibleMateria();
                transferible.setNombre(nombreTextField.getText());
                transferible.setCodigoDeMateria(codigoTextField.getText());
                transferible.setPromocionable(promocionableCheckBox.isSelected());
                transferible.setCorrelativas(materiasList.getSelectedValuesList());
                
                if(this.isEdicion){
                    transferible.setMateriaID(materiaId);
                    ControllerMateria.actualizarMateria(transferible);
                }
                else{
                    ControllerMateria.crearMateria(transferible);
                    javax.swing.JOptionPane.showMessageDialog(this, "La Materia fue creada con éxito. \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                }
                

                ViewMain.ShowJPanel(new MateriasPanel());
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios. \n", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error fatal al intentar crear la Materia. \n", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Subir_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JSeparator Separador_Separator;
    private javax.swing.JButton Subir_Button;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Materia> materiasList;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JCheckBox promocionableCheckBox;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
