package com.milton.gomez.sistema.universitario.View.Panels.Carrera;

import com.milton.gomez.sistema.universitario.Controller.ControllerCarrera;
import com.milton.gomez.sistema.universitario.Controller.ControllerAlumno;
import com.milton.gomez.sistema.universitario.Model.Alumno;
import com.milton.gomez.sistema.universitario.View.ViewMain;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milton
 */
public class CarrerasPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlumnoPanel
     */
    public CarrerasPanel() {
        initComponents();
        cargarCarreras();
        alinearTablaCarreras();
    }
    
    private void cargarCarreras(){
        
        // "ID", "Codigo", "Nombre", "Materias Optativas", "Cuatrimestres", "Plan de Estudio"
        DefaultTableModel model = (DefaultTableModel)carrerasTable.getModel();
        
        model.setRowCount(0);
        
        ControllerCarrera.listarTodasLasCarreras()
                .forEach((c) -> model
                        .addRow(new Object[]{
                            c.getCarreraID(),
                            c.getCodigoCarrera(), 
                            c.getNombre(), 
                            c.getCantMateriasOptativasParaAprobar(), 
                            c.getCuatrimestres().size(), 
                            c.getPlanDeEstudio()}));
    }
    private void alinearTablaCarreras(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        carrerasTable.setDefaultRenderer(Integer.class, centerRenderer);
        carrerasTable.setDefaultRenderer(Long.class, centerRenderer);
        carrerasTable.setDefaultRenderer(Object.class, centerRenderer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Background_Panel = new javax.swing.JPanel();
        Header_Panel = new javax.swing.JPanel();
        Titulo_Label = new javax.swing.JLabel();
        Separador_Separator = new javax.swing.JSeparator();
        Body_Panel = new javax.swing.JPanel();
        CarreraBusqueda_Panel = new javax.swing.JPanel();
        Carrera_TextField = new javax.swing.JTextField();
        Buscar_Button = new javax.swing.JButton();
        ListCarreras_Panel = new javax.swing.JPanel();
        Carrera_ScrollPane = new javax.swing.JScrollPane();
        carrerasTable = new javax.swing.JTable();
        CarreraBottonButtons_Panel = new javax.swing.JPanel();
        Eliminar_Button = new javax.swing.JButton();
        Editar_Button = new javax.swing.JButton();
        Nuevo_Button = new javax.swing.JButton();
        Detalles_Button = new javax.swing.JButton();
        Refresh_Button = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        Titulo_Label.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrera_icon.png"))); // NOI18N
        Titulo_Label.setText("Gestion de Carreras");

        javax.swing.GroupLayout Header_PanelLayout = new javax.swing.GroupLayout(Header_Panel);
        Header_Panel.setLayout(Header_PanelLayout);
        Header_PanelLayout.setHorizontalGroup(
            Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header_PanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header_PanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Titulo_Label))
                    .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Header_PanelLayout.setVerticalGroup(
            Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header_PanelLayout.createSequentialGroup()
                .addComponent(Titulo_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Carrera_TextField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Carrera_TextField.setText("Inserte el Nombre o Codigo de la Carrera...");
        Carrera_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Carrera_TextFieldFocusLost(evt);
            }
        });
        Carrera_TextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Carrera_TextFieldMousePressed(evt);
            }
        });
        Carrera_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carrera_TextFieldActionPerformed(evt);
            }
        });

        Buscar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Buscar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Buscar_Button.setText("Buscar");
        Buscar_Button.setBorder(null);
        Buscar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarreraBusqueda_PanelLayout = new javax.swing.GroupLayout(CarreraBusqueda_Panel);
        CarreraBusqueda_Panel.setLayout(CarreraBusqueda_PanelLayout);
        CarreraBusqueda_PanelLayout.setHorizontalGroup(
            CarreraBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarreraBusqueda_PanelLayout.createSequentialGroup()
                .addComponent(Carrera_TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CarreraBusqueda_PanelLayout.setVerticalGroup(
            CarreraBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarreraBusqueda_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarreraBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Carrera_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Buscar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Carrera_ScrollPane.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        carrerasTable.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        carrerasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo", "Nombre", "Optativas", "Cuatrimestres", "Plan de Estudio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carrerasTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carrerasTable.setShowGrid(false);
        Carrera_ScrollPane.setViewportView(carrerasTable);
        if (carrerasTable.getColumnModel().getColumnCount() > 0) {
            carrerasTable.getColumnModel().getColumn(0).setMaxWidth(100);
            carrerasTable.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        javax.swing.GroupLayout ListCarreras_PanelLayout = new javax.swing.GroupLayout(ListCarreras_Panel);
        ListCarreras_Panel.setLayout(ListCarreras_PanelLayout);
        ListCarreras_PanelLayout.setHorizontalGroup(
            ListCarreras_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Carrera_ScrollPane)
        );
        ListCarreras_PanelLayout.setVerticalGroup(
            ListCarreras_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Carrera_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Eliminar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Eliminar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Eliminar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Button.setText("Eliminar");
        Eliminar_Button.setBorder(null);
        Eliminar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ButtonActionPerformed(evt);
            }
        });

        Editar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Editar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Editar_Button.setText("Editar");
        Editar_Button.setBorder(null);
        Editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_ButtonActionPerformed(evt);
            }
        });

        Nuevo_Button.setBackground(new java.awt.Color(204, 0, 0));
        Nuevo_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo_Button.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo_Button.setText("Nuevo");
        Nuevo_Button.setBorder(null);
        Nuevo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_ButtonActionPerformed(evt);
            }
        });

        Detalles_Button.setBackground(new java.awt.Color(204, 0, 0));
        Detalles_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Detalles_Button.setForeground(new java.awt.Color(255, 255, 255));
        Detalles_Button.setText("Detalles");
        Detalles_Button.setBorder(null);
        Detalles_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detalles_ButtonActionPerformed(evt);
            }
        });

        Refresh_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh_icon.png"))); // NOI18N
        Refresh_Button.setBorderPainted(false);
        Refresh_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarreraBottonButtons_PanelLayout = new javax.swing.GroupLayout(CarreraBottonButtons_Panel);
        CarreraBottonButtons_Panel.setLayout(CarreraBottonButtons_PanelLayout);
        CarreraBottonButtons_PanelLayout.setHorizontalGroup(
            CarreraBottonButtons_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarreraBottonButtons_PanelLayout.createSequentialGroup()
                .addComponent(Refresh_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Nuevo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Detalles_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CarreraBottonButtons_PanelLayout.setVerticalGroup(
            CarreraBottonButtons_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarreraBottonButtons_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(CarreraBottonButtons_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nuevo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Detalles_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CarreraBottonButtons_PanelLayout.createSequentialGroup()
                .addComponent(Refresh_Button)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Body_PanelLayout = new javax.swing.GroupLayout(Body_Panel);
        Body_Panel.setLayout(Body_PanelLayout);
        Body_PanelLayout.setHorizontalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarreraBusqueda_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListCarreras_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CarreraBottonButtons_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Body_PanelLayout.setVerticalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addComponent(CarreraBusqueda_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListCarreras_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CarreraBottonButtons_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout Background_PanelLayout = new javax.swing.GroupLayout(Background_Panel);
        Background_Panel.setLayout(Background_PanelLayout);
        Background_PanelLayout.setHorizontalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Background_PanelLayout.setVerticalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addComponent(Header_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Body_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Carrera_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carrera_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carrera_TextFieldActionPerformed

    private void Nuevo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_ButtonActionPerformed
        ViewMain.ShowJPanel(new SubirCarreraPanel());
    }//GEN-LAST:event_Nuevo_ButtonActionPerformed

    private void Carrera_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Carrera_TextFieldFocusLost
        if(Carrera_TextField.getText().isEmpty()){
            Carrera_TextField.setForeground(Color.gray);
            Carrera_TextField.setText("Inserte el Nombre o Codigo de la Carrera...");
        }
    }//GEN-LAST:event_Carrera_TextFieldFocusLost

    private void Refresh_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_ButtonActionPerformed
        cargarCarreras();
        Carrera_TextField.setText("Inserte el Nombre o Codigo de la Carrera...");
    }//GEN-LAST:event_Refresh_ButtonActionPerformed

    private void Carrera_TextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carrera_TextFieldMousePressed
        if(Carrera_TextField.getText().equals("Inserte el Nombre o Codigo de la Carrera...")){
            Carrera_TextField.setText("");
            Carrera_TextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_Carrera_TextFieldMousePressed

    private void Buscar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_ButtonActionPerformed
        if(!Carrera_TextField.getText().equals("Inserte el Nombre o Codigo de la Carrera...")){
            try{
                String busqueda = Carrera_TextField.getText();
                carrerasTable.setModel(ControllerCarrera.obtenerCarrera(carrerasTable, busqueda));
            }
            catch(NullPointerException e){
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró la carrera. \n", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el Nombre o Código de la carrera primero. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Buscar_ButtonActionPerformed

    private void Eliminar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ButtonActionPerformed
        
        if(carrerasTable.getSelectedColumnCount() != 0){
            DefaultTableModel model = (DefaultTableModel)carrerasTable.getModel();
            try{
                // filas seleccionadas
                int[] filasSeleccionadas = carrerasTable.getSelectedRows();

                // Recorre las filas seleccionadas en orden inverso
                for (int i = filasSeleccionadas.length - 1; i >= 0; i--) {
                    int fila = filasSeleccionadas[i];
                    // Elimina el alumno usando el índice correspondiente
                    ControllerCarrera.eliminarCarrera((Integer) carrerasTable.getValueAt(fila, 0));
                    // Elimina la fila del modelo
                    model.removeRow(fila);
}
            }
            catch(Exception e){
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una Carrera primero. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_Eliminar_ButtonActionPerformed

    private void Detalles_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detalles_ButtonActionPerformed
        if(carrerasTable.getSelectedRow() != -1){
            Integer carreraId = (Integer) carrerasTable.getValueAt(carrerasTable.getSelectedRow(), 0);
            ViewMain.ShowJPanel(new DetallesCarrera(carreraId));
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una Carrera primero. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Detalles_ButtonActionPerformed

    private void Editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_ButtonActionPerformed
        
        if(carrerasTable.getSelectedRow() != -1){
            ViewMain.ShowJPanel(new SubirCarreraPanel((Integer) carrerasTable.getValueAt(carrerasTable.getSelectedRow(),0)));
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una Carrera primero. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Editar_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JPanel Body_Panel;
    private javax.swing.JButton Buscar_Button;
    private javax.swing.JPanel CarreraBottonButtons_Panel;
    private javax.swing.JPanel CarreraBusqueda_Panel;
    private javax.swing.JScrollPane Carrera_ScrollPane;
    private javax.swing.JTextField Carrera_TextField;
    private javax.swing.JButton Detalles_Button;
    private javax.swing.JButton Editar_Button;
    private javax.swing.JButton Eliminar_Button;
    private javax.swing.JPanel Header_Panel;
    private javax.swing.JPanel ListCarreras_Panel;
    private javax.swing.JButton Nuevo_Button;
    private javax.swing.JButton Refresh_Button;
    private javax.swing.JSeparator Separador_Separator;
    private javax.swing.JLabel Titulo_Label;
    private javax.swing.JTable carrerasTable;
    private javax.swing.JMenu jMenu1;
    // End of variables declaration//GEN-END:variables
}
