package com.milton.gomez.sistema.universitario.View.Panels;

import com.milton.gomez.sistema.universitario.Controller.ControllerAlumno;
import com.milton.gomez.sistema.universitario.View.MainJFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milton
 */
public class AlumnosPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlumnoPanel
     */
    public AlumnosPanel() {
        initComponents();
        cargarAlumnos();
        alinearTablaAlumnos();
    }
    
    private void cargarAlumnos(){
        
        // "ID", "Legajo", "DNI", "Nombre", "Apellido", "Carrera"
        DefaultTableModel model = (DefaultTableModel)Alumnos_Table.getModel();
        ControllerAlumno.listarTodosLosAlumnos()
                .forEach((u) -> model
                        .addRow(new Object[]{
                            u.getAlumnoID(),
                            u.getLegajo(), 
                            u.getDni(), 
                            u.getNombre(), 
                            u.getApellido(), 
                            u.getCarrera().getNombre()}));
    }
    
    private void alinearTablaAlumnos(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.RIGHT );
        Alumnos_Table.setDefaultRenderer(Object.class, centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Panel = new javax.swing.JPanel();
        Header_Panel = new javax.swing.JPanel();
        Titulo_Label = new javax.swing.JLabel();
        Separador_Separator = new javax.swing.JSeparator();
        Body_Panel = new javax.swing.JPanel();
        AlumnoBusqueda_Panel = new javax.swing.JPanel();
        Alumno_TextField = new javax.swing.JTextField();
        Buscar_Button = new javax.swing.JButton();
        ListAlumnos_Panel = new javax.swing.JPanel();
        Alumnos_ScrollPane = new javax.swing.JScrollPane();
        Alumnos_Table = new javax.swing.JTable();
        AlumnoEditDelete_Panel = new javax.swing.JPanel();
        Eliminar_Button = new javax.swing.JButton();
        Editar_Button = new javax.swing.JButton();
        Nuevo_Button = new javax.swing.JButton();

        Titulo_Label.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        Titulo_Label.setText("Gestion de Alumnos");

        javax.swing.GroupLayout Header_PanelLayout = new javax.swing.GroupLayout(Header_Panel);
        Header_Panel.setLayout(Header_PanelLayout);
        Header_PanelLayout.setHorizontalGroup(
            Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header_PanelLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header_PanelLayout.createSequentialGroup()
                        .addComponent(Titulo_Label)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header_PanelLayout.createSequentialGroup()
                        .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        Header_PanelLayout.setVerticalGroup(
            Header_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador_Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Alumno_TextField.setText("Inserte el DNI o ID del Alumno...");
        Alumno_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alumno_TextFieldActionPerformed(evt);
            }
        });

        Buscar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Buscar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Buscar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Buscar_Button.setText("Buscar");
        Buscar_Button.setBorder(null);

        javax.swing.GroupLayout AlumnoBusqueda_PanelLayout = new javax.swing.GroupLayout(AlumnoBusqueda_Panel);
        AlumnoBusqueda_Panel.setLayout(AlumnoBusqueda_PanelLayout);
        AlumnoBusqueda_PanelLayout.setHorizontalGroup(
            AlumnoBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoBusqueda_PanelLayout.createSequentialGroup()
                .addComponent(Alumno_TextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AlumnoBusqueda_PanelLayout.setVerticalGroup(
            AlumnoBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoBusqueda_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlumnoBusqueda_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Alumno_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(Buscar_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Alumnos_ScrollPane.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        Alumnos_Table.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Alumnos_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Legajo", "DNI", "Nombre", "Apellido", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Alumnos_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Alumnos_Table.setShowGrid(false);
        Alumnos_ScrollPane.setViewportView(Alumnos_Table);

        javax.swing.GroupLayout ListAlumnos_PanelLayout = new javax.swing.GroupLayout(ListAlumnos_Panel);
        ListAlumnos_Panel.setLayout(ListAlumnos_PanelLayout);
        ListAlumnos_PanelLayout.setHorizontalGroup(
            ListAlumnos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alumnos_ScrollPane)
        );
        ListAlumnos_PanelLayout.setVerticalGroup(
            ListAlumnos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alumnos_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Eliminar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Eliminar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Eliminar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Button.setText("Eliminar");
        Eliminar_Button.setBorder(null);

        Editar_Button.setBackground(new java.awt.Color(204, 0, 0));
        Editar_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Editar_Button.setForeground(new java.awt.Color(255, 255, 255));
        Editar_Button.setText("Editar");
        Editar_Button.setBorder(null);

        Nuevo_Button.setBackground(new java.awt.Color(204, 0, 0));
        Nuevo_Button.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Nuevo_Button.setForeground(new java.awt.Color(255, 255, 255));
        Nuevo_Button.setText("Nuevo");
        Nuevo_Button.setBorder(null);
        Nuevo_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AlumnoEditDelete_PanelLayout = new javax.swing.GroupLayout(AlumnoEditDelete_Panel);
        AlumnoEditDelete_Panel.setLayout(AlumnoEditDelete_PanelLayout);
        AlumnoEditDelete_PanelLayout.setHorizontalGroup(
            AlumnoEditDelete_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AlumnoEditDelete_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nuevo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eliminar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AlumnoEditDelete_PanelLayout.setVerticalGroup(
            AlumnoEditDelete_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlumnoEditDelete_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AlumnoEditDelete_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nuevo_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Body_PanelLayout = new javax.swing.GroupLayout(Body_Panel);
        Body_Panel.setLayout(Body_PanelLayout);
        Body_PanelLayout.setHorizontalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AlumnoBusqueda_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListAlumnos_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AlumnoEditDelete_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Body_PanelLayout.setVerticalGroup(
            Body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Body_PanelLayout.createSequentialGroup()
                .addComponent(AlumnoBusqueda_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListAlumnos_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AlumnoEditDelete_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Background_PanelLayout = new javax.swing.GroupLayout(Background_Panel);
        Background_Panel.setLayout(Background_PanelLayout);
        Background_PanelLayout.setHorizontalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Background_PanelLayout.setVerticalGroup(
            Background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_PanelLayout.createSequentialGroup()
                .addComponent(Header_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Body_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Alumno_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alumno_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alumno_TextFieldActionPerformed

    private void Nuevo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_ButtonActionPerformed
        MainJFrame.ShowJPanel(new NuevoAlumnoPanel());
    }//GEN-LAST:event_Nuevo_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlumnoBusqueda_Panel;
    private javax.swing.JPanel AlumnoEditDelete_Panel;
    private javax.swing.JTextField Alumno_TextField;
    private javax.swing.JScrollPane Alumnos_ScrollPane;
    private javax.swing.JTable Alumnos_Table;
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JPanel Body_Panel;
    private javax.swing.JButton Buscar_Button;
    private javax.swing.JButton Editar_Button;
    private javax.swing.JButton Eliminar_Button;
    private javax.swing.JPanel Header_Panel;
    private javax.swing.JPanel ListAlumnos_Panel;
    private javax.swing.JButton Nuevo_Button;
    private javax.swing.JSeparator Separador_Separator;
    private javax.swing.JLabel Titulo_Label;
    // End of variables declaration//GEN-END:variables
}
