/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.milton.gomez.sistema.universitario.View.Panels;

import com.milton.gomez.sistema.universitario.Controller.ControllerCarreras;
import com.milton.gomez.sistema.universitario.Model.ModelCarrera;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milton
 */
public class NuevoAlumnoPanel extends javax.swing.JPanel {

    /**
     * Creates new form NuevoAlumnoPanel
     */
    public NuevoAlumnoPanel() {
        initComponents();
        listarCarreras();
        alinearTablaMaterias();
    }
    
    private void listarCarreras(){
        // Obtener el modelo de la JList
        DefaultListModel<ModelCarrera> listModel = (DefaultListModel<ModelCarrera>) Carreras_List.getModel();

        // Limpiar el modelo actual para evitar duplicados
        listModel.clear();

        // Agregar cada carrera al modelo de la JList
        ControllerCarreras.listarTodasLasCarreras().forEach((c) -> listModel.addElement(c));
    }
    
    private void listarMaterias(){
        // Obtenemos el modelo de la JList materias
        DefaultTableModel tableModel = (DefaultTableModel) Materias_Table.getModel();
        
        tableModel.setRowCount(0);
        
        ControllerCarreras.listarTodosLosCuatrimestres(Carreras_List.getSelectedValue().getCarreraID())
                .forEach((c) -> c.listarTodasLasMaterias().forEach((m) -> tableModel
                        .addRow(new Object[]{
                            c.getCuatrimestreID()+1,
                            m})));
        
        
    }
    
    private void alinearTablaMaterias(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.LEFT );
        Materias_Table.setDefaultRenderer(Object.class, centerRenderer);
        Materias_Table.setDefaultRenderer(Integer.class, centerRenderer);
    }
    
    //private void

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Legajo_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DNI_TextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Nombre_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Apellido_TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Carrera_ScrollPane = new javax.swing.JScrollPane();
        Carreras_List = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        Materia_ScrollPane = new javax.swing.JScrollPane();
        Materias_Table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person_icon.png"))); // NOI18N
        jLabel1.setText("Crear nuevo Alumno");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Legajo (6 caracteres)");

        Legajo_TextField.setText("Ingrese el Legajo...");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("DNI (8 caracteres)");

        DNI_TextField.setText("Ingrese el DNI...");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");

        Nombre_TextField.setText("Ingrese el Nombre...");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Apellido");

        Apellido_TextField.setText("Ingrese el Apellido...");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Seleccione la Carrera (Max. 1)");

        Carreras_List.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        Carreras_List.setModel(new DefaultListModel<>());
        Carreras_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Carreras_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Carreras_ListValueChanged(evt);
            }
        });
        Carrera_ScrollPane.setViewportView(Carreras_List);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Seleccione las Materias");

        Materia_ScrollPane.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        Materias_Table.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        Materias_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuatrimestre", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Materia_ScrollPane.setViewportView(Materias_Table);
        if (Materias_Table.getColumnModel().getColumnCount() > 0) {
            Materias_Table.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.setBorderPainted(false);

        javax.swing.GroupLayout Background_panelLayout = new javax.swing.GroupLayout(Background_panel);
        Background_panel.setLayout(Background_panelLayout);
        Background_panelLayout.setHorizontalGroup(
            Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_panelLayout.createSequentialGroup()
                .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_panelLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(Background_panelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Background_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Legajo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(DNI_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background_panelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Carrera_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(Materia_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)))))
                .addGap(23, 23, 23))
        );
        Background_panelLayout.setVerticalGroup(
            Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Background_panelLayout.createSequentialGroup()
                        .addGroup(Background_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Background_panelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(Legajo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(DNI_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)
                                .addComponent(Nombre_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Apellido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Background_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(Carrera_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Materia_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Carreras_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Carreras_ListValueChanged
        listarMaterias();
    }//GEN-LAST:event_Carreras_ListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido_TextField;
    private javax.swing.JPanel Background_panel;
    private javax.swing.JScrollPane Carrera_ScrollPane;
    private javax.swing.JList<ModelCarrera> Carreras_List;
    private javax.swing.JTextField DNI_TextField;
    private javax.swing.JTextField Legajo_TextField;
    private javax.swing.JScrollPane Materia_ScrollPane;
    private javax.swing.JTable Materias_Table;
    private javax.swing.JTextField Nombre_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
